import { Game } from "@/types/types";
  
export const games: Game[] = [
  { id: "gtavi", title: "GTA VI", imageUrl: "/gta-vi.jpg?height=200&width=350", developer: "RockStar" },
  { id: "gosthofyotei", title: "Ghost of Yotei", imageUrl: "/ghost-of-yotei.jpg?height=200&width=350", developer: "Sucker Punch Productions" },
  { id: "doomthedarkages", title: "Doom: The Dark Ages", imageUrl: "/doom-dark-ages.jpg?height=200&width=350", developer: "Id Software / Bethesda Softworks" },
  { id: "likeadragonpirateyakuza", title: "Like a Dragon: Pirate Yakuza in Hawaii", imageUrl: "/like-a-dragon-pirate-yakusa.jpg?height=200&width=350", developer: "Ryu Ga Gotoku Studio, Sega" },
  { id: "splitfiction", title: "Split Fiction", imageUrl: "/split-fiction.jpg?height=200&width=350", developer: "Hazelight Studios" },
  { id: "borderlands4", title: "Borderlands 4", imageUrl: "/borderlands-4.png?height=200&width=350", developer: "Gearbox Software" },
  { id: "thefirstberserkerkhazan", title: "The First Berserker Khazan", imageUrl: "/berserker-khazan.jpg?height=200&width=350", developer: "Neople" },
  { id: "clairobscurexpedition33", title: "Clair Obscur: Expedition 33", imageUrl: "/expedition-33.jpg?height=200&width=350", developer: "Sandfall Interactive" },
  { id: "wwe2k25", title: "WWE 2K25", imageUrl: "/wwe2k25.png?height=200&width=350", developer: "Visual Concepts" },
  { id: "sidmeierscivilization7", title: "Sid Meier’s Civilization 7", imageUrl: "/sid-meiers-civilization-7.jpg?height=200&width=350", developer: "Firaxis Games" },
  { id: "fatalfurycityofwolves", title: "Fatal Fury: City of Wolves", imageUrl: "/fatal-fury-city-of-wolves.jpg?height=200&width=350", developer: "SNK" },
  { id: "markofthedeep", title: "Mark of the Deep", imageUrl: "/mark-of-the-deep.jpg?height=200&width=350", developer: "Mad Mimic" },
  { id: "avowed", title: "Avowed", imageUrl: "/avowed.png?height=200&width=350", developer: "Obsidian" },
  { id: "assasinscreedshadows", title: "Assasin’s Creed Shadows", imageUrl: "/assassins-creed-shadows.png?height=200&width=350", developer: "Ubisoft" },
  { id: "monsterhunterwilds", title: "Monster Hunter Wilds", imageUrl: "/monster-hunter-wilds.png?height=200&width=350", developer: "Capcom" },
  { id: "kingdomcomedeliverance2", title: "Kingdom Come: Deliverance 2", imageUrl: "/kingdom-come-deliverance-2.jpg?height=200&width=350", developer: "Warhorse Studios" },
  { id: "dragonageveilguard", title: "Dragon Age The Veil Guard", imageUrl: "/dragon-age-the-veilguard.png?height=200&width=350", developer: "Bioware" },
  { id: "marvelrivals", title: "Marvel Rivals", imageUrl: "/marvel-rivals.png?height=200&width=350", developer: "NetEase" },
  { id: "riseoftheronin", title: "Rise Of The Ronin", imageUrl: "/rise-of-the-ronin.jpg?height=200&width=350", developer: "Team Ninja, Koei Tecmo Games" },
  { id: "hades2", title: "Hades II", imageUrl: "/hades-2.png?height=200&width=350", developer: "Supergiant Games" },
  { id: "indianajonesgreatcircle", title: "Indiana Jones and the Great Circle", imageUrl: "/indiana-jones.jpg?height=200&width=350", developer: "MachineGames" },
  { id: "citizensleeper2", title: "Citizen Sleeper 2: Starward Vector", imageUrl: "/citizen-sleeper-2.jpg?height=200&width=350", developer: "Jump Over The Age" },
  { id: "endermagnolia", title: "Ender Magnolia: Bloom in the Mist", imageUrl: "/ender-magnolia.jpg?height=200&width=350", developer: "Adglobe, Live Wire Inc." },
  { id: "littlenightmares3", title: "Little Nightmares 3", imageUrl: "/little-nightmares-3.jpg?height=200&width=350", developer: "Supermassive Games" },
  { id: "metroidprime4", title: "Metroid Prime 4: Beyond", imageUrl: "/metroid-prime-4.png?height=200&width=350", developer: "Retro Studios, Nintendo" },
  { id: "mafiaoldcountry", title: "Mafia: The Old Country", imageUrl: "/mafia-the-old-country.png?height=200&width=350", developer: "Hangar 13" },
  { id: "finalfantasyviirebirth", title: "Final Fantasy VII Rebirth", imageUrl: "/ffvii-rebirth.png?height=200&width=350", developer: "Square Enix" },
  { id: "vellum", title: "Vellum", imageUrl: "/vellum.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "among-us-3d", title: "Among Us 3D", imageUrl: "/among-us-3d.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "siegecaster", title: "Siegecaster", imageUrl: "/siegecaster.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "deck-of-haunts", title: "Deck of Haunts", imageUrl: "/deck-of-haunts.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "survival-machine", title: "Survival Machine", imageUrl: "/survival-machine.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "revenge-of-the-savage-planet", title: "Revenge of the Savage Planet", imageUrl: "/revenge-of-the-savage-planet.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "yes-your-grace-snowfall", title: "Yes, Your Grace: Snowfall", imageUrl: "/yes-your-grace-snowfall.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "legacy-of-sin-ill-boding", title: "Legacy of Sin: Ill-Boding", imageUrl: "/legacy-of-sin-ill-boding.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "labyrinth-of-the-demon-king", title: "Labyrinth of the Demon King", imageUrl: "/labyrinth-of-the-demon-king.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "of-life-and-land", title: "Of Life and Land", imageUrl: "/of-life-and-land.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "frog-legs", title: "Frog Legs", imageUrl: "/frog-legs.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "monster-train-2", title: "Monster Train 2", imageUrl: "/monster-train-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "deliver-at-all-costs", title: "Deliver At All Costs", imageUrl: "/deliver-at-all-costs.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "duck-detective-the-secret-salami", title: "Duck Detective: The Secret Salami", imageUrl: "/duck-detective-the-secret-salami.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "grandma-no", title: "Grandma, No!", imageUrl: "/grandma-no.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lost-soul-aside", title: "Lost Soul Aside", imageUrl: "/lost-soul-aside.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nwo-anarchy-collapsed", title: "NWO – Anarchy Collapsed", imageUrl: "/nwo-anarchy-collapsed.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dune-awakening", title: "Dune: Awakening", imageUrl: "/dune-awakening.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fbc-firebreak", title: "FBC: Firebreak", imageUrl: "/fbc-firebreak.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wuchang-fallen-feathers", title: "Wuchang: Fallen Feathers", imageUrl: "/wuchang-fallen-feathers.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "super-robot-wars-y", title: "Super Robot Wars Y", imageUrl: "/super-robot-wars-y.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-legend-of-cyber-cowboy", title: "The Legend of Cyber Cowboy", imageUrl: "/the-legend-of-cyber-cowboy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "learn-to-play-vol-10-gravity-space-walk", title: "Learn to Play Vol. 10 – Gravity Space Walk", imageUrl: "/learn-to-play-vol-10-gravity-space-walk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sea-fantasy", title: "Sea Fantasy", imageUrl: "/sea-fantasy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ys-memoire-the-oath-in-felghana", title: "Ys Memoire: The Oath in Felghana", imageUrl: "/ys-memoire-the-oath-in-felghana.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rivenaars-grove", title: "Rivenaar’s Grove", imageUrl: "/rivenaars-grove.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "freedom-wars-remastered", title: "Freedom Wars Remastered", imageUrl: "/freedom-wars-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "asfalia-fear", title: "Asfalia Fear", imageUrl: "/asfalia-fear.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "heroes-of-hammerwatch-2", title: "Heroes of Hammerwatch 2", imageUrl: "/heroes-of-hammerwatch-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "hyper-light-breaker", title: "Hyper Light Breaker", imageUrl: "/hyper-light-breaker.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "threefold-recital", title: "Threefold Recital", imageUrl: "/threefold-recital.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "aloft", title: "Aloft", imageUrl: "/aloft.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "runny-bunny", title: "Runny Bunny", imageUrl: "/runny-bunny.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-roottrees-are-dead", title: "The Roottrees are Dead", imageUrl: "/the-roottrees-are-dead.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "donkey-kong-country-returns-hd", title: "Donkey Kong Country Returns HD", imageUrl: "/donkey-kong-country-returns-hd.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "montezumas-revenge-the-40th-anniversary-edition", title: "Montezuma’s Revenge – The 40th Anniversary Edition", imageUrl: "/montezumas-revenge-the-40th-anniversary-edition.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "things-too-ugly", title: "Things Too Ugly", imageUrl: "/things-too-ugly.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dynasty-warriors-origins", title: "Dynasty Warriors Origins", imageUrl: "/dynasty-warriors-origins.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tales-of-graces-f-remastered", title: "Tales of Graces f Remastered", imageUrl: "/tales-of-graces-f-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "idun", title: "IDUN", imageUrl: "/idun.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "into-the-emberlands", title: "Into the Emberlands", imageUrl: "/into-the-emberlands.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "magic-inn", title: "Magic Inn", imageUrl: "/magic-inn.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "super-roboy", title: "Super Roboy", imageUrl: "/super-roboy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lonely-mountains-snow-riders", title: "Lonely Mountains: Snow Riders", imageUrl: "/lonely-mountains-snow-riders.jpg?height=200&width=350", developer: "Megagon Industries" },
  { id: "somber-echoes", title: "Somber Echoes", imageUrl: "/somber-echoes.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "popotinhos-adventures", title: "Popotinho’s Adventures", imageUrl: "/popotinhos-adventures.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dreamcore", title: "Dreamcore", imageUrl: "/dreamcore.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "gravitators", title: "Gravitators", imageUrl: "/gravitators.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rocket-boots-mania", title: "Rocket Boots Mania", imageUrl: "/rocket-boots-mania.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "star-wars-episode-1-jedi-power-battles", title: "Star Wars Episode 1: Jedi Power Battles", imageUrl: "/star-wars-episode-1-jedi-power-battles.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "synduality-echo-of-ada", title: "Synduality Echo of Ada", imageUrl: "/synduality-echo-of-ada.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cat-detective-albert-wilde", title: "Cat Detective Albert Wilde", imageUrl: "/cat-detective-albert-wilde.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cuisineer", title: "Cuisineer", imageUrl: "/cuisineer.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "neptunia-riders-vs-dogoos", title: "Neptunia Riders Vs Dogoos", imageUrl: "/neptunia-riders-vs-dogoos.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "orcs-must-die-deathtrap", title: "Orcs Must Die! Deathtrap", imageUrl: "/orcs-must-die-deathtrap.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sibels-journey", title: "Sibel’s Journey", imageUrl: "/sibels-journey.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tails-of-iron-2-whiskers-of-winter", title: "Tails of Iron 2: Whiskers of Winter", imageUrl: "/tails-of-iron-2-whiskers-of-winter.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-stone-of-madness", title: "The Stone of Madness", imageUrl: "/the-stone-of-madness.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "warside", title: "Warside", imageUrl: "/warside.jpg?height=200&width=350", developer: "LAVABIRD" },
  { id: "agent-fall", title: "Agent Fall", imageUrl: "/agent-fall.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "coridden", title: "Coridden", imageUrl: "/coridden.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cryptical-path", title: "Cryptical Path", imageUrl: "/cryptical-path.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "detechtive-2112", title: "DeTechtive 2112", imageUrl: "/detechtive-2112.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dead-letter-dept", title: "Dead Letter Dept.", imageUrl: "/dead-letter-dept.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "defenders-quest-2", title: "Defender’s Quest 2", imageUrl: "/defenders-quest-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sniper-elite-resistance", title: "Sniper Elite: Resistance", imageUrl: "/sniper-elite-resistance.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "marvels-spider-man-2", title: "Marvel’s Spider-Man 2", imageUrl: "/marvels-spider-man-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "genso-manege", title: "Genso Manege", imageUrl: "/genso-manege.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "deathomen", title: "DeathOmen", imageUrl: "/deathomen.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rift-of-the-necrodancer", title: "Rift of the NecroDancer", imageUrl: "/rift-of-the-necrodancer.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "starlight-legacy", title: "Starlight Legacy", imageUrl: "/starlight-legacy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "while-waiting", title: "While Waiting", imageUrl: "/while-waiting.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ambulance-life-a-paramedic-simulator", title: "Ambulance Life: A Paramedic Simulator", imageUrl: "/ambulance-life-a-paramedic-simulator.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "big-helmet-heroes", title: "Big Helmet Heroes", imageUrl: "/big-helmet-heroes.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "keep-driving", title: "Keep Driving", imageUrl: "/keep-driving.jpg?height=200&width=350", developer: "DEVELOPER" },
{ id: "moons-of-darsalon", title: "Moons of Darsalon", imageUrl: "/moons-of-darsalon.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-executive", title: "The Executive", imageUrl: "/the-executive.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "super-jagger-bomb-2-go-east", title: "Super Jagger Bomb 2: Go East", imageUrl: "/super-jagger-bomb-2-go-east.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dawnfolk", title: "Dawnfolk", imageUrl: "/dawnfolk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "warriors-abyss", title: "Warriors: Abyss", imageUrl: "/warriors-abyss.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "phantom-breaker-battle-grounds-ultimate", title: "Phantom Breaker: Battle Grounds Ultimate", imageUrl: "/phantom-breaker-battle-grounds-ultimate.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rugby-25", title: "Rugby 25", imageUrl: "/rugby-25.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "afterlove-ep", title: "Afterlove EP", imageUrl: "/afterlove-ep.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-legend-of-heroes-trails-through-daybreak-ii", title: "The Legend of Heroes: Trails Through Daybreak II", imageUrl: "/the-legend-of-heroes-trails-through-daybreak-ii.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "immortal-hunters", title: "Immortal Hunters", imageUrl: "/immortal-hunters.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ale-abbey", title: "Ale Abbey", imageUrl: "/ale-abbey.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lost-records-bloom-rage-tape-1", title: "Lost Records: Bloom & Rage Tape 1", imageUrl: "/lost-records-bloom-rage-tape-1.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "hpl-nyarlathotep-rising", title: "HPL: Nyarlathotep Rising", imageUrl: "/hpl-nyarlathotep-rising.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "brokenlore-low", title: "BrokenLore: Low", imageUrl: "/brokenlore-low.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tribe-nine", title: "Tribe Nine", imageUrl: "/tribe-nine.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "die-in-the-dungeon", title: "Die in the Dungeon", imageUrl: "/die-in-the-dungeon.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ninja-five-0", title: "Ninja Five-0", imageUrl: "/ninja-five-0.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "omega-6-the-triangle-stars", title: "Omega 6: The Triangle Stars", imageUrl: "/omega-6-the-triangle-stars.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "grimoire-groves", title: "Grimoire Groves", imageUrl: "/grimoire-groves.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "two-point-museum", title: "Two Point Museum", imageUrl: "/two-point-museum.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "war-robots-frontiers", title: "War Robots: Frontiers", imageUrl: "/war-robots-frontiers.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wizordum", title: "Wizordum", imageUrl: "/wizordum.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "eldrador-creatures-shadowfall", title: "Eldrador Creatures: Shadowfall", imageUrl: "/eldrador-creatures-shadowfall.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fragpunk", title: "Fragpunk", imageUrl: "/fragpunk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "suikoden-i&ii-hd-remaster-gate-rune-and-dunan-unification-wars", title: "Suikoden I&II HD Remaster Gate Rune and Dunan Unification Wars", imageUrl: "/suikoden-i&ii-hd-remaster-gate-rune-and-dunan-unification-wars.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sugardew-island-your-cozy-farm-shop", title: "Sugardew Island – Your Cozy Farm Shop", imageUrl: "/sugardew-island-your-cozy-farm-shop.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "beyond-the-ice-palace-2", title: "Beyond the Ice Palace 2", imageUrl: "/beyond-the-ice-palace-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "centium", title: "Centium", imageUrl: "/centium.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wanderstop", title: "Wanderstop", imageUrl: "/wanderstop.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "expelled", title: "Expelled!", imageUrl: "/expelled.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fate-reawakened", title: "Fate: Reawakened", imageUrl: "/fate-reawakened.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "path-of-fury-episode-1", title: "Path of Fury: Episode 1", imageUrl: "/path-of-fury-episode-1.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "out-of-the-park-baseball-26", title: "Out of the Park Baseball 26", imageUrl: "/out-of-the-park-baseball-26.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "33-immortals", title: "33 Immortals", imageUrl: "/33-immortals.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mlb-the-show-25", title: "MLB The Show 25", imageUrl: "/mlb-the-show-25.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "reignbreaker", title: "Reignbreaker", imageUrl: "/reignbreaker.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "virballs", title: "Virballs", imageUrl: "/virballs.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mudborne", title: "Mudborne", imageUrl: "/mudborne.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "atelier-yumia-the-alchemist-of-memories-the-envisioned-land", title: "Atelier Yumia: The Alchemist of Memories & the Envisioned Land", imageUrl: "/atelier-yumia-the-alchemist-of-memories-the-envisioned-land.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dark-deity-2", title: "Dark Deity 2", imageUrl: "/dark-deity-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "folklands", title: "Folklands", imageUrl: "/folklands.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "breakout-beyond", title: "Breakout Beyond", imageUrl: "/breakout-beyond.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mother-machine", title: "Mother Machine", imageUrl: "/mother-machine.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "grit-and-valor-1949", title: "Grit and Valor – 1949", imageUrl: "/grit-and-valor-1949.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "twilight-monk", title: "Twilight Monk", imageUrl: "/twilight-monk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wednesdays", title: "Wednesdays", imageUrl: "/wednesdays.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ai-limit", title: "AI Limit", imageUrl: "/ai-limit.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "atomfall", title: "Atomfall", imageUrl: "/atomfall.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bubble-ghost-remake", title: "Bubble Ghost Remake", imageUrl: "/bubble-ghost-remake.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ena-dream-bbq-chapter-1", title: "ENA: Dream BBQ Chapter 1", imageUrl: "/ena-dream-bbq-chapter-1.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "saga-frontier-2-remastered", title: "SaGa Frontier 2 Remastered", imageUrl: "/saga-frontier-2-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sports-renovations", title: "Sports: Renovations", imageUrl: "/sports-renovations.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dollhouse-behind-the-broken-mirror", title: "Dollhouse: Behind the Broken Mirror", imageUrl: "/dollhouse-behind-the-broken-mirror.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wildkeepers-rising", title: "Wildkeepers Rising", imageUrl: "/wildkeepers-rising.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nif-nif", title: "Nif Nif", imageUrl: "/nif-nif.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "crocs-legend-of-the-gobbos", title: "Crocs: Legend of the Gobbos", imageUrl: "/crocs-legend-of-the-gobbos.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "elroy-and-the-aliens", title: "Elroy and the Aliens", imageUrl: "/elroy-and-the-aliens.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "steel-hunters", title: "Steel Hunters", imageUrl: "/steel-hunters.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "detective-dotson", title: "Detective Dotson", imageUrl: "/detective-dotson.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "jin-jan", title: "Jin & Jan", imageUrl: "/jin-jan.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ekoh-beach", title: "Ekoh Beach", imageUrl: "/ekoh-beach.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "peppered", title: "Peppered", imageUrl: "/peppered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "vindefiant", title: "Vindefiant", imageUrl: "/vindefiant.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cursed-dawn", title: "Cursed Dawn", imageUrl: "/cursed-dawn.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dissent-on-mars", title: "Dissent on Mars", imageUrl: "/dissent-on-mars.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "armored-brigade-2", title: "Armored Brigade 2", imageUrl: "/armored-brigade-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "burden-of-command", title: "Burden of Command", imageUrl: "/burden-of-command.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "locomoto", title: "Locomoto", imageUrl: "/locomoto.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "south-of-midnight", title: "South of Midnight", imageUrl: "/south-of-midnight.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "commandos-origins", title: "Commandos: Origins", imageUrl: "/commandos-origins.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "driveloop", title: "Driveloop", imageUrl: "/driveloop.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "blue-prince", title: "Blue Prince", imageUrl: "/blue-prince.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "crashlands-2", title: "Crashlands 2", imageUrl: "/crashlands-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "monaco-2", title: "Monaco 2", imageUrl: "/monaco-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "monster-energy-supercross-25-the-official-video-game", title: "Monster Energy Supercross 25 – The Official Video Game", imageUrl: "/monster-energy-supercross-25-the-official-video-game.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "perplex", title: "Perplex", imageUrl: "/perplex.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "promise-mascot-agency", title: "Promise Mascot Agency", imageUrl: "/promise-mascot-agency.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "star-overdrive", title: "Star Overdrive", imageUrl: "/star-overdrive.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "steel-seed", title: "Steel Seed", imageUrl: "/steel-seed.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "willow-guard", title: "Willow Guard", imageUrl: "/willow-guard.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "travelers-refrain", title: "Traveler’s Refrain", imageUrl: "/travelers-refrain.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fubuki-zero-in-on-holoearth", title: "Fubuki – zero in on Holoearth –", imageUrl: "/fubuki-zero-in-on-holoearth-.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-fools-apprentice", title: "The Fool’s Apprentice", imageUrl: "/the-fools-apprentice.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lost-records-bloom-rage-tape-2", title: "Lost Records: Bloom & Rage Tape 2", imageUrl: "/lost-records-bloom-rage-tape-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-electrifying-incident-a-monster-mini-expedition", title: "The Electrifying Incident: A Monster Mini-Expedition", imageUrl: "/the-electrifying-incident-a-monster-mini-expedition.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "synergy", title: "Synergy", imageUrl: "/synergy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bionic-bay", title: "Bionic Bay", imageUrl: "/bionic-bay.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "chasmal-fear", title: "Chasmal Fear", imageUrl: "/chasmal-fear.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "gorn-2", title: "Gorn 2", imageUrl: "/gorn-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mandragora", title: "Mandragora", imageUrl: "/mandragora.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rusty-rabbit", title: "Rusty Rabbit", imageUrl: "/rusty-rabbit.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lunar-remastered-collection", title: "Lunar Remastered Collection", imageUrl: "/lunar-remastered-collection.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mirage-ignis-fatuus", title: "Mirage: Ignis Fatuus", imageUrl: "/mirage-ignis-fatuus.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tranquil-isle", title: "Tranquil Isle", imageUrl: "/tranquil-isle.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rise-of-rebellion", title: "Rise of Rebellion", imageUrl: "/rise-of-rebellion.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "creepy-redneck-dinosaur-mansion-3", title: "Creepy Redneck Dinosaur Mansion 3", imageUrl: "/creepy-redneck-dinosaur-mansion-3.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "out-of-hands", title: "Out of Hands", imageUrl: "/out-of-hands.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-elder-scrolls-iv-oblivion-remastered", title: "The Elder Scrolls IV: Oblivion Remastered", imageUrl: "/the-elder-scrolls-iv-oblivion-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "war-rats", title: "War Rats", imageUrl: "/war-rats.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "beholder-conductor", title: "Beholder: Conductor", imageUrl: "/beholder-conductor.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "old-skies", title: "Old Skies", imageUrl: "/old-skies.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sunderfolk", title: "Sunderfolk", imageUrl: "/sunderfolk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "realpolitiks-3-earth-and-beyond", title: "Realpolitiks 3: Earth and Beyond", imageUrl: "/realpolitiks-3-earth-and-beyond.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "super-technos-world-river-city-arcade-classics", title: "Super Technos World: River City & Arcade Classics", imageUrl: "/super-technos-world-river-city-arcade-classics.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-hundred-line-last-defense-academy", title: "The Hundred Line – Last Defense Academy", imageUrl: "/the-hundred-line-last-defense-academy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "days-gone-remastered", title: "Days Gone Remastered", imageUrl: "/days-gone-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "starless-abyss", title: "Starless Abyss", imageUrl: "/starless-abyss.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "warfare-legacy-collection", title: "Warfare Legacy Collection", imageUrl: "/warfare-legacy-collection.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "blight-night", title: "Blight Night", imageUrl: "/blight-night.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "forza-horizon-5", title: "Forza Horizon 5", imageUrl: "/forza-horizon-5.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "moroi", title: "Moroi", imageUrl: "/moroi.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "skin-deep", title: "Skin Deep", imageUrl: "/skin-deep.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "starvaders", title: "StarVaders", imageUrl: "/starvaders.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shotgun-cop-man", title: "Shotgun Cop Man", imageUrl: "/shotgun-cop-man.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "what-the-clash", title: "What The Clash?", imageUrl: "/what-the-clash.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "metal-eden", title: "Metal Eden", imageUrl: "/metal-eden.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "unblock", title: "Unblock", imageUrl: "/unblock.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bahamut-and-the-waqwaq-tree", title: "Bahamut and the Waqwaq Tree", imageUrl: "/bahamut-and-the-waqwaq-tree.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sonic-rumble", title: "Sonic Rumble", imageUrl: "/sonic-rumble.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-midnight-walk", title: "The Midnight Walk", imageUrl: "/the-midnight-walk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "vambrace-dungeon-monarch", title: "Vambrace: Dungeon Monarch", imageUrl: "/vambrace-dungeon-monarch.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "omega-crafter", title: "Omega Crafter", imageUrl: "/omega-crafter.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "void-sails", title: "Void Sails", imageUrl: "/void-sails.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nubs-arena", title: "Nubs: Arena", imageUrl: "/nubs-arena.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tennis-manager-25", title: "Tennis Manager 25", imageUrl: "/tennis-manager-25.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "capcom-fighting-collection-2", title: "Capcom Fighting Collection 2", imageUrl: "/capcom-fighting-collection-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "roadcraft", title: "Roadcraft", imageUrl: "/roadcraft.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lynked-banner-of-the-spark", title: "Lynked: Banner of the Spark", imageUrl: "/lynked-banner-of-the-spark.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "out-of-sight", title: "Out of Sight", imageUrl: "/out-of-sight.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "teenage-mutant-ninja-turtles-tactical-takedown", title: "Teenage Mutant Ninja Turtles: Tactical Takedown", imageUrl: "/teenage-mutant-ninja-turtles-tactical-takedown.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "worshippers-of-cthulhu", title: "Worshippers of Cthulhu", imageUrl: "/worshippers-of-cthulhu.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "to-a-t", title: "To a T", imageUrl: "/to-a-t.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "disney-illusion-island", title: "Disney Illusion Island", imageUrl: "/disney-illusion-island.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "elden-ring-nightreign", title: "Elden Ring: Nightreign", imageUrl: "/elden-ring-nightreign.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rune-factory-guardians-of-azuma", title: "Rune Factory: Guardians of Azuma", imageUrl: "/rune-factory-guardians-of-azuma.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nintendo-switch-2-lancamento-do-console", title: "Nintendo Switch 2 (lançamento do console)", imageUrl: "/nintendo-switch-2-lancamento-do-console.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bravely-default-flying-fairy-hd-remaster", title: "Bravely Default Flying Fairy HD Remaster", imageUrl: "/bravely-default-flying-fairy-hd-remaster.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cyberpunk-2077-ultimate-edition", title: "Cyberpunk 2077: Ultimate Edition", imageUrl: "/cyberpunk-2077-ultimate-edition.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fast-fusion", title: "Fast Fusion", imageUrl: "/fast-fusion.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "final-fantasy-7-remake-intergrade", title: "Final Fantasy 7 Remake Intergrade", imageUrl: "/final-fantasy-7-remake-intergrade.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fortnite", title: "Fortnite", imageUrl: "/fortnite.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "hitman-world-of-assassination-signature-edition", title: "Hitman World of Assassination – Signature Edition", imageUrl: "/hitman-world-of-assassination-signature-edition.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "hogwarts-legacy", title: "Hogwarts Legacy", imageUrl: "/hogwarts-legacy.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mario-kart-world", title: "Mario Kart World", imageUrl: "/mario-kart-world.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nintendo-switch-2-welcome-tour", title: "Nintendo Switch 2 Welcome Tour", imageUrl: "/nintendo-switch-2-welcome-tour.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "street-fighter-6", title: "Street Fighter 6", imageUrl: "/street-fighter-6.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-legend-of-zelda-breath-of-the-wild", title: "The Legend of Zelda: Breath of the Wild", imageUrl: "/the-legend-of-zelda-breath-of-the-wild.jpg?height=200&width=350", developer: "DEVELOPER" },
{ id: "the-legend-of-zelda-tears-of-the-kingdom", title: "The Legend of Zelda: Tears of the Kingdom", imageUrl: "/the-legend-of-zelda-tears-of-the-kingdom.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "parallel-experiment", title: "Parallel Experiment", imageUrl: "/parallel-experiment.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "yakuza-0-directors-cut", title: "Yakuza 0: Director’s Cut", imageUrl: "/yakuza-0-directors-cut.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mindseye", title: "MindsEye", imageUrl: "/mindseye.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-alters", title: "The Alters", imageUrl: "/the-alters.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shadowverse-worlds-beyond", title: "Shadowverse: Worlds Beyond", imageUrl: "/shadowverse-worlds-beyond.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "raidou-remastered", title: "Raidou Remastered", imageUrl: "/raidou-remastered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rematch", title: "Rematch", imageUrl: "/rematch.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "death-stranding-2-on-the-beach", title: "Death Stranding 2: On The Beach", imageUrl: "/death-stranding-2-on-the-beach.jpg?height=200&width=350", developer: "Kojima Productions" },
  { id: "ruffy-and-the-riverside", title: "Ruffy and the Riverside", imageUrl: "/ruffy-and-the-riverside.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tamagotchi-plaza", title: "Tamagotchi Plaza", imageUrl: "/tamagotchi-plaza.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "patapon-1-2-replay", title: "Patapon 1 + 2 Replay", imageUrl: "/patapon-1-2-replay.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tony-hawks-pro-skater-3-4", title: "Tony Hawk’s Pro Skater 3 + 4", imageUrl: "/tony-hawks-pro-skater-3-4.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "edens-zero", title: "Edens Zero", imageUrl: "/edens-zero.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "donkey-kong-bananza", title: "Donkey Kong Bananza", imageUrl: "/donkey-kong-bananza.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-wandering-village", title: "The Wandering Village", imageUrl: "/the-wandering-village.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shadow-labyrinth", title: "Shadow Labyrinth", imageUrl: "/shadow-labyrinth.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "super-mario-party-jamboree-jamboree-tv", title: "Super Mario Party Jamboree + Jamboree TV", imageUrl: "/super-mario-party-jamboree-jamboree-tv.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "no-sleep-for-kaname-date-from-ai-the-somnium-files", title: "No Sleep For Kaname Date – From AI: The Somnium Files", imageUrl: "/no-sleep-for-kaname-date-from-ai-the-somnium-files.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tales-of-the-shire-a-lord-of-the-rings-game", title: "Tales of the Shire: A Lord of the Rings Game", imageUrl: "/tales-of-the-shire-a-lord-of-the-rings-game.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "gradius-origins", title: "Gradius Origins", imageUrl: "/gradius-origins.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "story-of-seasons-grand-bazaar", title: "Story of Seasons: Grand Bazaar", imageUrl: "/story-of-seasons-grand-bazaar.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "kirby-and-the-forgotten-land-star-crossed-world", title: "Kirby and the Forgotten Land + Star-Crossed World", imageUrl: "/kirby-and-the-forgotten-land-star-crossed-world.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "metal-gear-solid-delta-snake-eater", title: "Metal Gear Solid Delta: Snake Eater", imageUrl: "/metal-gear-solid-delta-snake-eater.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-knightling", title: "The Knightling", imageUrl: "/the-knightling.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shinobi-art-of-vengeance", title: "Shinobi: Art of Vengeance", imageUrl: "/shinobi-art-of-vengeance.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "hell-is-us", title: "Hell is Us", imageUrl: "/hell-is-us.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "deep-rock-galactic-survivor", title: "Deep Rock Galactic: Survivor", imageUrl: "/deep-rock-galactic-survivor.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "marathon", title: "Marathon", imageUrl: "/marathon.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "directive-8020", title: "Directive 8020", imageUrl: "/directive-8020.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "double-dragon-revive", title: "Double Dragon Revive", imageUrl: "/double-dragon-revive.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "2xko", title: "2XKO", imageUrl: "/2xko.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "abiotic-factor", title: "Abiotic Factor", imageUrl: "/abiotic-factor.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "agent-64-spies-never-die", title: "Agent 64: Spies Never Die", imageUrl: "/agent-64-spies-never-die.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "an-amazing-wizard", title: "An Amazing Wizard", imageUrl: "/an-amazing-wizard.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "archeage-chronicles", title: "ArcheAge Chronicles", imageUrl: "/archeage-chronicles.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "astromeda", title: "Astromeda", imageUrl: "/astromeda.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "atelier-resleriana-the-red-alchemist-the-white-guardian", title: "Atelier Resleriana: The Red Alchemist & the White Guardian", imageUrl: "/atelier-resleriana-the-red-alchemist-the-white-guardian.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "automate-it", title: "Automate It", imageUrl: "/automate-it.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "baby-steps", title: "Baby Steps", imageUrl: "/baby-steps.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bad-cheese", title: "Bad Cheese", imageUrl: "/bad-cheese.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "battlefield-waltz", title: "Battlefield Waltz", imageUrl: "/battlefield-waltz.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "battle-vision-network", title: "Battle Vision Network", imageUrl: "/battle-vision-network.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "begone-beast", title: "Begone Beast", imageUrl: "/begone-beast.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "big-walk", title: "Big Walk", imageUrl: "/big-walk.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "biped-2", title: "Biped 2", imageUrl: "/biped-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bittersweet-birthday", title: "Bittersweet Birthday", imageUrl: "/bittersweet-birthday.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bokura-planet", title: "Bokura: Planet", imageUrl: "/bokura-planet.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "broken-arrow", title: "Broken Arrow", imageUrl: "/broken-arrow.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "burning-sword-death-sun", title: "Burning Sword: Death Sun", imageUrl: "/burning-sword-death-sun.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "bylina", title: "Bylina", imageUrl: "/bylina.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cabernet", title: "Cabernet", imageUrl: "/cabernet.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "car-dealer-simulator", title: "Car Dealer Simulator", imageUrl: "/car-dealer-simulator.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "carmen-sandiego", title: "Carmen Sandiego", imageUrl: "/carmen-sandiego.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "castle-come", title: "Castle Come", imageUrl: "/castle-come.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "chromegun-2-dye-hard", title: "ChromeGun 2: Dye Hard", imageUrl: "/chromegun-2-dye-hard.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "clockwork-ambrosia", title: "Clockwork Ambrosia", imageUrl: "/clockwork-ambrosia.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "coffee-talk-tokyo", title: "Coffee Talk Tokyo", imageUrl: "/coffee-talk-tokyo.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "constance", title: "Constance", imageUrl: "/constance.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "corpse-party-ii-darkness-distortion", title: "Corpse Party II: Darkness Distortion", imageUrl: "/corpse-party-ii-darkness-distortion.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "crimson-desert", title: "Crimson Desert", imageUrl: "/crimson-desert.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "crown-of-greed", title: "Crown of Greed", imageUrl: "/crown-of-greed.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "cyber-paradise", title: "Cyber Paradise", imageUrl: "/cyber-paradise.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "decadent", title: "Decadent", imageUrl: "/decadent.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "deltarune-chapters-3-4", title: "Deltarune Chapters 3 & 4", imageUrl: "/deltarune-chapters-3-4.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "demonschool", title: "Demonschool", imageUrl: "/demonschool.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "despelote", title: "Despelote", imageUrl: "/despelote.jpg?height=200&width=350", developer: "Julián Cordero, Sebastian Valbuena" },
  { id: "despera-drops", title: "Despera Drops", imageUrl: "/despera-drops.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "discounty", title: "Discounty", imageUrl: "/discounty.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dragon-ball-project-multi", title: "Dragon Ball Project: Multi", imageUrl: "/dragon-ball-project-multi.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dragonkin-the-banished", title: "Dragonkin: The Banished", imageUrl: "/dragonkin-the-banished.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "dreamed-away", title: "Dreamed Away", imageUrl: "/dreamed-away.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "drops-of-death", title: "Drops Of Death", imageUrl: "/drops-of-death.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ed-edda-racing-champions-gran-prix", title: "Ed & Edda: Racing Champions – Gran Prix", imageUrl: "/ed-edda-racing-champions-gran-prix.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "elevator-down", title: "Elevator Down", imageUrl: "/elevator-down.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "eternal-strands", title: "Eternal Strands", imageUrl: "/eternal-strands.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "exekiller", title: "ExeKiller", imageUrl: "/exekiller.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "exiler", title: "Exiler", imageUrl: "/exiler.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fantasy-life-i-the-girl-who-steals-time", title: "Fantasy Life i: The Girl Who Steals Time", imageUrl: "/fantasy-life-i-the-girl-who-steals-time.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fast-food-restaurant-simulator", title: "Fast Food – Restaurant Simulator", imageUrl: "/fast-food-restaurant-simulator.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "fighting-force-collection", title: "Fighting Force Collection", imageUrl: "/fighting-force-collection.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "first-blood-persian-legends", title: "First Blood: Persian Legends", imageUrl: "/first-blood-persian-legends.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "football-manager-25", title: "Football Manager 25", imageUrl: "/football-manager-25.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "forever-skies", title: "Forever Skies", imageUrl: "/forever-skies.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "forty-niner", title: "Forty-Niner", imageUrl: "/forty-niner.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "glaciered", title: "Glaciered", imageUrl: "/glaciered.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ghost-keeper", title: "Ghost Keeper", imageUrl: "/ghost-keeper.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "ghosts", title: "Ghosts", imageUrl: "/ghosts.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "grand-theft-auto-vi", title: "Grand Theft Auto VI", imageUrl: "/grand-theft-auto-vi.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "greedfall-2-the-dying-world", title: "GreedFall 2: The Dying World", imageUrl: "/greedfall-2-the-dying-world.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "haunted-lands", title: "Haunted Lands", imageUrl: "/haunted-lands.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "homura-hime", title: "Homura Hime", imageUrl: "/homura-hime.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "icebound", title: "Icebound", imageUrl: "/icebound.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "infinity-knights-xross", title: "Infinity Knights: Xross", imageUrl: "/infinity-knights-xross.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "inkonbini-one-store-many-stories", title: "InKONBINI: One Store. Many Stories", imageUrl: "/inkonbini-one-store-many-stories.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "john-carpenters-toxic-commando", title: "John Carpenter’s Toxic Commando", imageUrl: "/john-carpenters-toxic-commando.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "judas", title: "Judas", imageUrl: "/judas.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "junxions", title: "Junxions", imageUrl: "/junxions.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "killing-floor-3", title: "Killing Floor 3", imageUrl: "/killing-floor-3.jpg?height=200&width=350", developer: "Tripwire Interactive" },
  { id: "kristala", title: "Kristala", imageUrl: "/kristala.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "liegecraft", title: "Liegecraft", imageUrl: "/liegecraft.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "lost-in-random-the-eternal-die", title: "Lost in Random: The Eternal Die", imageUrl: "/lost-in-random-the-eternal-die.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "love-eternal", title: "Love Eternal", imageUrl: "/love-eternal.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "luto", title: "Luto", imageUrl: "/luto.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mainframes", title: "Mainframes", imageUrl: "/mainframes.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "marines-vs-god", title: "Marines Vs. God", imageUrl: "/marines-vs-god.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mayhem-brawler-ii-best-of-both-worlds", title: "Mayhem Brawler II: Best of Both Worlds", imageUrl: "/mayhem-brawler-ii-best-of-both-worlds.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mewgenics", title: "Mewgenics", imageUrl: "/mewgenics.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mio-memories-in-orbit", title: "MIO: Memories In Orbit", imageUrl: "/mio-memories-in-orbit.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mistonia-no-kibou-the-lost-delight", title: "Mistonia no Kibou – The Lost Delight", imageUrl: "/mistonia-no-kibou-the-lost-delight.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "monster-dna", title: "Monster DNA", imageUrl: "/monster-dna.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "moon-samurai", title: "Moon Samurai", imageUrl: "/moon-samurai.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "morsels", title: "Morsels", imageUrl: "/morsels.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "moth-kubit", title: "Moth Kubit", imageUrl: "/moth-kubit.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "motorslice", title: "Motorslice", imageUrl: "/motorslice.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "mouse-pi-for-hire", title: "Mouse: P.I. For Hire", imageUrl: "/mouse-pi-for-hire.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nascar-25", title: "Nascar 25", imageUrl: "/nascar-25.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nanuka-secret-of-the-shattering-moon", title: "Nanuka: Secret of the Shattering Moon", imageUrl: "/nanuka-secret-of-the-shattering-moon.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "naughty-geese", title: "Naughty Geese", imageUrl: "/naughty-geese.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "neo-junk-city", title: "Neo Junk City", imageUrl: "/neo-junk-city.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nirvana-noir", title: "Nirvana Noir", imageUrl: "/nirvana-noir.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nivalis", title: "Nivalis", imageUrl: "/nivalis.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "nocturne", title: "Nocturne", imageUrl: "/nocturne.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "one-fenix-down", title: "One Fenix Down", imageUrl: "/one-fenix-down.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "orkendale-the-scarred-land", title: "Orkendale: The Scarred Land", imageUrl: "/orkendale-the-scarred-land.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "paradise-duality-unbound", title: "Paradise: Duality Unbound", imageUrl: "/paradise-duality-unbound.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "pax-dei", title: "Pax Dei", imageUrl: "/pax-dei.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "phantom-brave-the-lost-hero", title: "Phantom Brave: The Lost Hero", imageUrl: "/phantom-brave-the-lost-hero.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "plus-ultra-legado", title: "Plus Ultra: Legado", imageUrl: "/plus-ultra-legado.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "pokemon-legends-z-a", title: "Pokemon Legends: Z-A", imageUrl: "/pokemon-legends-z-a.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "professor-layton-and-the-new-world-of-steam", title: "Professor Layton and the New World of Steam", imageUrl: "/professor-layton-and-the-new-world-of-steam.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "project-code-vampire-hunter", title: "Project Code Vampire Hunter", imageUrl: "/project-code-vampire-hunter.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "realm-of-ink", title: "Realm of Ink", imageUrl: "/realm-of-ink.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "redemption-of-the-damned", title: "Redemption of the Damned", imageUrl: "/redemption-of-the-damned.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "replaced", title: "Replaced", imageUrl: "/replaced.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rising-heat", title: "Rising Heat", imageUrl: "/rising-heat.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "rodent-rumble", title: "Rodent Rumble", imageUrl: "/rodent-rumble.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sanctua", title: "Sanctua", imageUrl: "/sanctua.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "saveseeker", title: "Saveseeker", imageUrl: "/saveseeker.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "serialworld", title: "SerialWorld", imageUrl: "/serialworld.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shield-strike", title: "Shield Strike", imageUrl: "/shield-strike.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shipwrecked-lost-colony", title: "Shipwrecked: Lost Colony", imageUrl: "/shipwrecked-lost-colony.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "shovel-knight-shovel-of-hope-dx", title: "Shovel Knight: Shovel of Hope DX", imageUrl: "/shovel-knight-shovel-of-hope-dx.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "solnox-grimoire-of-seasons", title: "Solnox: Grimoire of Seasons", imageUrl: "/solnox-grimoire-of-seasons.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sparkball", title: "Sparkball", imageUrl: "/sparkball.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "spectral-keep", title: "Spectral Keep", imageUrl: "/spectral-keep.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "spine-this-is-gun-fu", title: "Spine: This Is Gun Fu", imageUrl: "/spine-this-is-gun-fu.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "spray-paint-simulator", title: "Spray Paint Simulator", imageUrl: "/spray-paint-simulator.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "star-of-providence", title: "Star of Providence", imageUrl: "/star-of-providence.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "starsand-island", title: "Starsand Island", imageUrl: "/starsand-island.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "starship", title: "Starship", imageUrl: "/starship.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "stellar-settlers-space-base-builder", title: "Stellar Settlers: Space Base Builder", imageUrl: "/stellar-settlers-space-base-builder.jpg?height=200&width=350", developer: "Tinymice Entertainment" },
  { id: "sulfur", title: "Sulfur", imageUrl: "/sulfur.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "sultans-game", title: "Sultan’s Game", imageUrl: "/sultans-game.jpg?height=200& width=350", developer: "DEVELOPER" },
  { id: "tales-of-seikyu", title: "Tales of Seikyu", imageUrl: "/tales-of-seikyu.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tears-of-magic", title: "Tears of Magic", imageUrl: "/tears-of-magic.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "tenebris-somnia", title: "Tenebris Somnia", imageUrl: "/tenebris-somnia.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "terrifier-the-artcade-game", title: "Terrifier: The ARTcade Game", imageUrl: "/terrifier-the-artcade-game.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-legend-of-baboo", title: "The Legend of Baboo", imageUrl: "/the-legend-of-baboo.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-legend-of-heroes-trails-in-the-sky-the-1st", title: "The Legend of Heroes: Trails in the Sky the 1st", imageUrl: "/the-legend-of-heroes-trails-in-the-sky-the-1st.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-relic-first-guardian", title: "The Relic: First Guardian", imageUrl: "/the-relic-first-guardian.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "time-flies", title: "Time Flies", imageUrl: "/time-flies.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "troublemaker-2-beyond-dream", title: "Troublemaker 2: Beyond Dream", imageUrl: "/troublemaker-2-beyond-dream.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "unbeatable", title: "Unbeatable", imageUrl: "/unbeatable.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "undergrounded", title: "Undergrounded", imageUrl: "/undergrounded.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "unyielding", title: "Unyielding", imageUrl: "/unyielding.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "utawarerumono-zan", title: "Utawarerumono: ZAN", imageUrl: "/utawarerumono-zan.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "vampire-the-masquerade-bloodlines-2", title: "Vampire: The Masquerade – Bloodlines 2", imageUrl: "/vampire-the-masquerade-bloodlines-2.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wardens-rising", title: "Wardens Rising", imageUrl: "/wardens-rising.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "wheel-world", title: "Wheel World", imageUrl: "/wheel-world.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "will-follow-the-light", title: "Will: Follow The Light", imageUrl: "/will-follow-the-light.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "windswept", title: "Windswept", imageUrl: "/windswept.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "winter-burrow", title: "Winter Burrow", imageUrl: "/winter-burrow.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "world-of-stickman-classic-rts", title: "World of Stickman Classic RTS", imageUrl: "/world-of-stickman-classic-rts.jpg?height=200&width=350", developer: "DEVELOPER" },
  { id: "the-talos-principle-reawakened", title: "The Talos Principle: Reawakened", imageUrl: "/the-talos-principle-reawakened.jpg?height=200&width=350", developer: "Croteam" },
  { id: "the-roottrees-are-dead", title: "The Roottrees are Dead", imageUrl: "/the-roottrees-are-dead.jpg?height=200&width=350", developer: "Robin Ward" },
  { id: "age-of-mythology-retold-immortal-pillars", title: "Age of Mythology: Retold - Immortal Pillars", imageUrl: "/age-of-mythology-retold-immortal-pillars.jpg?height=200&width=350", developer: "World's Edge, Virtuos Games, Forgotten Empires, Tantalus Media" },
  { id: "nba-2k25", title: "NBA 2K25", imageUrl: "/nba-2k25.jpg?height=200&width=350", developer: "Visual Concepts" },
  { id: "ea-sports-fc-25", title: "EA SPORTS FC™ 25", imageUrl: "/ea-sports-fc-25.jg?height=200&width=350", developer: "EA" },
  { id: "pga-tour-2k25", title: "PGA TOUR 2K25", imageUrl: "/pga-tour-2k25.png?height=200&width=350", developer: "HB Studios" },
  { id: "tempest-rising", title: "Tempest Rising", imageUrl: "/tempest-rising.jpg?height=200&width=350", developer: "Slipgate Ironworks™" },
  { id: "iron-saga-vs", title: "Iron Saga VS", imageUrl: "/iron-saga-vs.jpg?height=200&width=350", developer: "Gameduchy" },
  { id: "cyber-city-clash", title: "Cyber City Clash", imageUrl: "/cyber-city-clash.jpg?height=200&width=350", developer: "Apple Juice Interactive" },
  { id: "knock-off", title: "Knock Off", imageUrl: "/knock-off.jpg?height=200&width=350", developer: "Mechaghidora" },
  { id: "hunter-x-hunter-nen-x-impact", title: "Hunter x Hunter Nen x Impact", imageUrl: "/hunter-x-hunter-nen-x-impact.jpg?height=200&width=350", developer: "Bushiroad Games" },
  { id: "enigma-do-medo", title: "Enigma do Medo", imageUrl: "/enigma-do-medo.jpg?height=200&width=350", developer: "Dumativa, Cellbit" },
  { id: "aila", title: "A.I.L.A", imageUrl: "/aila.jpg?height=200&width=350", developer: "Pulsatrix Studios" },
  { id: "e-lich-corporate-souls", title: "E-Lich:Corporate Souls", imageUrl: "/e-lich-corporate-souls.jpg?height=200&width=350", developer: "JohnnyR Designs" },
  { id: "no-heroes-here-2", title: "No Heroes Here 2", imageUrl: "/no-heroes-here-2.jpg?height=200&width=350", developer:"Mad Mimic"  },
  { id: "pipistrello-and-the-cursed-yoyo", title: "Pipistrello and the Cursed Yoyo", imageUrl: "/pipistrello-and-the-cursed-yoyo.png?height=200&width=350", developer: "Pocket Trap" },
]
  